### ISSUE TITLE
AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'is_punct'

### ISSUE THREAD

**Issue by arnavc1712** [peter3125/enhanced-subject-verb-object-extraction#13]
**Stack Trace**

> Traceback (most recent call last):
  File "explore.py", line 173, in <module>
    svos = findSVOs(nlp, sentence.text, removepunctuation=True, uncontracttext=True)
  File "/home/exx/arnav/CIPS/knowledge-graph/svo_extraction/subject_verb_object_extract.py", line 291, in findSVOs
    return _get_svos(tokens, removepunctuation)
  File "/home/exx/arnav/CIPS/knowledge-graph/svo_extraction/subject_verb_object_extract.py", line 331, in _get_svos
    "!" + v.lower_ if verbNegated or objNegated else v.lower_, to_str(expand(obj, tokens, visited, removepunctuation))))
  File "/home/exx/arnav/CIPS/knowledge-graph/svo_extraction/subject_verb_object_extract.py", line 273, in expand
    return removePunctuationCharacters(parts)
  File "/home/exx/arnav/CIPS/knowledge-graph/svo_extraction/subject_verb_object_extract.py", line 240, in removePunctuationCharacters
    not_punctuation_token = [token for token in tokens if not token.is_punct]
  File "/home/exx/arnav/CIPS/knowledge-graph/svo_extraction/subject_verb_object_extract.py", line 240, in <listcomp>
    not_punctuation_token = [token for token in tokens if not token.is_punct]
AttributeError: 'spacy.tokens.doc.Doc' object has no attribute 'is_punct'

For this specific sentence '_both sides should understand that.”.'_, I get the above attribute error when calling the . On further debugging I narrowed down the problem to  this line
`item = _get_that_resolution(tokens)` followed by `parts.append(item)`.
Here the _get_that_resolution function returns a spacy.tokens.doc.Doc object due to the last line of 
```# resolve a 'that' where/if appropriate
def _get_that_resolution(toks):
    for tok in toks:
        if 'that' in [t.orth_ for t in tok.lefts]:
            return tok.head
    return toks
```
What could be a possible fix?

**Comment by rock3125** [comment]
I've added a fix.  I had to rollback some code to the previous version.  I mistakenly merged some other code that broke all the unit tests, and the code wasn't written for the latest version of spacy.
